apps/front/forms.py
# -*- encoding: utf-8 -*-
"""
@File    : forms.py
@Time    : 2020/5/11 10:00
@Author  : chen
前台表单信息：apps/front/forms.py
"""
# 前台form表单信息
from wtforms import Form, StringField, IntegerField, ValidationError
from wtforms.validators import EqualTo, Email, InputRequired, Length, Regexp
from utils import random_captcha                                               # 随机生成验证码
from utils import redis_captcha                                                # 保存验证码到redis数据库中


# 表单信息的父类文件
class BaseForm(Form):
    def get_error(self):
        message = self.errors.popitem()[1][0]          # 错误信息的收集，字典类型数据信息提取
        return message


# 注册界面的Form表单类
class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message="请输入正确格式的手机号")])
    sms_captcha = StringField(validators=[Regexp(r'\w{4}', message="请输入正确格式的验证码")])              # \w包含字母
    username = StringField(validators=[Length(min=2, max=15, message="请输入正确长度的用户名")])
    password1 = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{3,20}', message="请输入正确格式的密码")])
    password2 = StringField(validators=[EqualTo('password1', message="两次输入密码不一致")])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message="请输入正确格式的验证码")])
    
    # 验证手机验证码字段
    def validate_sms_captcha(self, field):
        telephone = self.telephone.data
        sms_captcha = self.sms_captcha.data                            # 获得表单信息
        
        sms_captcha_redis = redis_captcha.redis_get(telephone)         # redis数据库中根据手机号调验证码，进行判定是否相同
        
        # 判断用户输入的验证码和redis中取出的验证码是否相同
        if not sms_captcha_redis or sms_captcha_redis.lower() != sms_captcha.lower():
            raise ValidationError(message="手机验证码输入错误")
        
        # if sms_captcha or sms_captcha.lower() == sms_captcha_redis.lower():
        #     pass
        # else:
        #     raise ValidationError("验证码输入错误")
      
    # 图形验证码字段验证
    def validate_graph_captcha(self, field):
        graph_captcha = self.graph_captcha.data                                 # 表单信息收集

        graph_captcha_redis = redis_captcha.redis_get(graph_captcha)            # redis中是将验证码的text当做key来保存的，调用也是一样

        # 判定图形验证码是否一致
        if not graph_captcha_redis or graph_captcha_redis.lower() != graph_captcha.lower():
            # print("ceshi")
            raise ValidationError(message="图形验证码输入错误")


# 登录界面的Form表单信息收集
class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message="请输入正确格式的手机号")])
    password = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{3,20}', message="请输入正确格式的密码")])
    remember = StringField(IntegerField())
    

# 帖子的Form表单信息收集
class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message="请输入标题")])
    content = StringField(validators=[InputRequired(message="请输入内容")])
    board_id = StringField(validators=[InputRequired(message="请输入板块名称")])
    

# 评论的Form表单验证
class AddCommentForm(BaseForm):
    # 表单信息的收集根据网页端发送的参数名称和类型
    content = StringField(validators=[InputRequired(message="请输入评论内容")])
    post_id = IntegerField(validators=[InputRequired(message="请选择一篇帖子进行评论")])

apps/front/__init__.py
# -*- encoding: utf-8 -*-
"""
@File    : __init__.py.py
@Time    : 2020/5/11 9:57
@Author  : chen

"""

apps/front/views.py
# -*- encoding: utf-8 -*-
"""
@File    : views.py
@Time    : 2020/5/11 9:59
@Author  : chen
前台蓝图文件：apps/front/views.py
"""
# 前台的蓝图文件  类视图函数写在这里
from flask import (
    Blueprint,
    render_template,
    views,
    make_response,                  # make_response生成response对象，用于返回前端模板
    request,
    session,
    g,
)

# 导入图像验证码生成文件
from utils.captcha import Captcha

# 图形验证码image是二进制数据，需要转换成字节流才能使用
from io import BytesIO

# 将图形验证码保存到Redis         restful输出信息弹窗
from utils import redis_captcha, restful

# 验证码表单信息验证
from .forms import (
    SignupForm,               # 注册的Form表单信息收集
    SigninForm,               # 登录的Form表单信息收集
    AddPostForm,              # 帖子提交表单信息
    AddCommentForm,           # 添加帖子评论
)

# 导入前台用户模型
from .models import (
    Front_User,
    PostModel,
    CommentModel,             # 评论模型
)

# 导入数据库连接 db
from exts import db

# 确保URL安全的文件：utils/safe_url.py
from utils import safe_url

from apps.cms.models import (
    BannerModel,                      # 导入后台轮播图模型BannerModel
    BoardModel,                       # 导入后台板块管理模型
    HighlightPostModel,               # 帖子加精模型
)
# 导入分页功能库
from flask_paginate import Pagination, get_page_parameter
# 导入前台界面权限验证装饰器
from .decorators import login_required
# 导入配置文件
import config
from sqlalchemy import func                      # 导入求和方法

front_bp = Blueprint("front", __name__)          # 前端不用前缀，直接在首页显示，front是蓝图，在front_signup.html调用生成图形验证码时候需要用

# 权限验证  需要在front_bp产生后，再导入
from .hooks import before_request


# BBS的首页界面路由
@front_bp.route("/")
def index():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)   # 通过权重查询，每页显示4条
    boards = BoardModel.query.all()                                              # 查询板块中的所有
    board_id = request.args.get('board_id', type=int, default=None)              # get方法需要使用args，注意这里的数据类型需要改成int
    
    # 接收参数st的状态值，用于判断不同种类的排序
    sort = request.args.get('st', type=int, default=1)
    
    page = request.args.get(get_page_parameter(), type=int, default=1)           # 获取当前页码
    start = (page-1)*config.PER_PAGE                                             # 起始页码是(当前页码-1)*10
    end = start + config.PER_PAGE                                                # 每页都是起始页码+10
    
    # 接收参数st，根据sort的参数不同，判断不同种类的排序
    query_obj = None
    if sort == 1:                                                                # 用户选择最新帖子的顺序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())       # 帖子创建时间倒序
    elif sort == 2:                                                              # 用户选择精华帖子的顺序
        query_obj = db.session.query(PostModel).join(HighlightPostModel).order_by(  # 内关联PostModel,HighlightPostModel交集
            HighlightPostModel.create_time.desc()                                   # 根据创建时间倒序排序
        )                     # 帖子加精模型
    elif sort == 3:                                                              # 用户选择阅读最多的顺序
        query_obj = PostModel.query.order_by(PostModel.read_count.desc())        # 查询阅读数量
    elif sort == 4:                                                              # 用户选择评论最多的顺序
        query_obj = db.session.query(PostModel).join(CommentModel).group_by(
            PostModel.id                                                         # 先分组，根据不同帖子id进行分组再排序
        ).order_by(
            func.count(CommentModel.id).desc()                                   # 通过评论总数排序
        )
       
    # 实现根据不同board_id进行帖子分类显示，即用户选择不同板块，显示的帖子种类相对应
    if board_id:
        posts = query_obj.filter(PostModel.board_id == board_id).slice(start, end)        # slice(start, end)分页
        total = query_obj.filter(PostModel.board_id == board_id).count()                  # 计算该板块的总数
    else:
        posts = query_obj.slice(start, end)                                    # 帖子信息传输，如果用户不选择板块，查询所有
        total = query_obj.count()                                              # 计算帖子总数

    # pagination是一个对象,bs_version=3是bootstrap的版本为3,per_page参数添加，pagination.links正常显示所有
    pagination = Pagination(bs_version=3, page=page, total=total,
                            per_page=config.PER_PAGE,                          # config.py中的每页10条数据
                            inner_window=3, outer_window=1)                    # inner_window=3是内层显示页码的样式，默认为2，
    # print(pagination.links)                                                  # 当数据量小的时候，不显示，添加per_page参数就能解决
    
    context = {                                                                # 多种数据传输到前台界面
        "banners": banners,
        "boards": boards,
        "current_board_id": board_id,
        "posts": posts,
        "pagination": pagination,
        "current_sort": sort,
        
    }
    
    return render_template("front/front_index.html", **context)            # 渲染到首页界面,查询数据传输到前台界面


# 图形验证码路由
@front_bp.route("/captcha/")
def graph_captcha():
    try:                                                 # 异常处理
        # 图像验证码生成文件中返回两个参数   text, image
        text, image = Captcha.gene_graph_captcha()      # 生成图形验证码，image是二进制数据，需要转换成字节流才能使用
        print("发送的图形验证码是：{}".format(text))
        
        # 将图形验证码保存到Redis数据库中
        redis_captcha.redis_set(text.lower(), text.lower())  # redis_set中需要传参key和value，text没有唯一对应的key，只能都传参text
        
        # BytesIO是生成的字节流
        out = BytesIO()
        image.save(out, 'png')                          # 把图片image保存在字节流中，并指定为png格式
        # 文件流指针
        out.seek(0)                                     # 从字节流最初开始读取
        # 生成response对象，用于返回前端模板中
        resp = make_response(out.read())
        resp.content_type = 'image/png'                 # 指定数据类型
    except:
        return graph_captcha()                          # 没有生成验证码就再调用一次
        
    return resp                                         # 返回对象


# 测试referrer的跳转
@front_bp.route("/test/")
def test():
    return render_template("front/front_test.html")


# 用户注册类视图
class SingupView(views.MethodView):
    def get(self):
        # 图像验证码生成文件中返回两个参数   text, image
        # text, image = Captcha.gene_graph_captcha()
        # print(text)                      # 验证码
        # print(image)                     # 图形文件，图形类<PIL.Image.Image image mode=RGBA size=100x30 at 0x1EFC9000C88>

        # 从当前页面跳转过来就是None   从其他页面跳转过来输出就是上一个页面信息     referrer是页面的跳转
        # print(request.referrer)                           # http://127.0.0.1:9999/test/
        
        return_to = request.referrer
        # 确保URL安全的文件：utils/safe_url.py
        print(safe_url.is_safe_url(return_to))              # 判断return_to是否来自站内，是否是安全url，防爬虫
        
        if return_to and return_to != request.url and safe_url.is_safe_url(return_to):       # 跳转的url不能是当前页面，request.url是当前的url地址
            return render_template("front/front_signup.html", return_to=return_to)           # return_to渲染到前端界面
        else:
            return render_template("front/front_signup.html")                                # 如果没获取url,直接渲染注册界面
        
    # 验证码的form表单信息提交验证
    def post(self):
        form = SignupForm(request.form)                       # 收集表单信息
        
        # 表单验证通过
        if form.validate():
            # 保存到数据库
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data                    # forms表单信息
            
            # 前台用户模型数据添加到数据库
            user = Front_User(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()                                                   # 提交到数据库
            
            # 表单验证通过，提交到数据库成功
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())                  # 表单信息验证出错


# 用户登录的类视图
class SinginView(views.MethodView):
    def get(self):
        return_to = request.referrer                                                    # referrer是上一个url
    
        if return_to and return_to != request.url and safe_url.is_safe_url(return_to):  # 跳转的url不能是当前页面，判断url是否安全
            return render_template("front/front_signin.html", return_to=return_to)      # return_to渲染到前端界面
        else:
            return render_template("front/front_signin.html")                           # 如果没获取url,直接渲染注册界面
    
    def post(self):
        form = SigninForm(request.form)                                            # 登录界面的Form表单信息
        
        if form.validate():                                                        # 表单信息存在
            # 收集form表单信息
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            
            user = Front_User.query.filter_by(telephone=telephone).first()         # 通过手机号验证该用户是否存在数据库
            if user and user.check_password(password):                             # 判断密码和用户是否正确
                # 'front_user_id'命名防止与后台验证session相同，会产生覆盖情况bug
                session['front_user_id'] = user.id                                 # 用户的id存储到session中，用于登录验证
                if remember:                                                       # 如果remember状态是1
                    # session持久化
                    session.permanent = True
                return restful.success()                                           # 成功
            else:
                return restful.params_error(message="手机号或者密码错误")           # 密码是、用户不正确
        else:
            return restful.params_error(message=form.get_error())                  # 表单信息不存在，输出异常信息
        

#  帖子编辑提交  的类视图     富文本编辑
class PostView(views.MethodView):
    # 登录验证，实现帖子编辑前进行权限验证
    decorators = [login_required]
    # 表单信息收集，传输
    def get(self):
        # 查询boards数据进行传输
        boards = BoardModel.query.all()                                           # boards是list类型
        return render_template("front/front_apost.html", boards=boards)           # boards数据传输到前端front_apost.html页面
    
    # 帖子的Form表单信息收集查询
    def post(self):
        form = AddPostForm(request.form)                     # 查询帖子提交的Form表单信息
        if form.validate():

templates/front/front_apost.html
<!-- 前台帖子信息渲染页面文件：templates/front/front_apost.html  -->
{% extends 'front/front_base.html' %}

{% block title %}
       发布帖子
{% endblock %}

<!--补充内容-->
{% block head %}
    <!--  富文本编辑器关联样式  -->
    <link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
    <script src="{{ url_for('static',filename='front/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
    <!-- 发布帖子页面关联样式  -->
    <script src="{{ url_for('static',filename='front/js/front_apost.js') }}"></script>

{% endblock %}

<!-- 模板继承 -->
{% block main_content %}
    <div class="main-container">
    <form action="" method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <!--     name="board_id"是帖子的Form表单信息中的字段       -->
            <select name="board_id" class="form-control">

                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

        <!--  绑定的id为editor  -->
     <div id="editor" class="form-group">
         <!--     name="content"是帖子的Form表单信息中的字段       -->
        <textarea name="content" id="TextContent" ></textarea>
     </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>

<script type="text/javascript">
    var testEditor;
    $(function () {
        testEditor = editormd("editor", {                                             // 绑定的id为editor
            width: "100%",
            height: 640,
            syncScrolling: "single",
            path: "{{ url_for('static',filename='editormd/lib/') }}",                 // 存储路径
            // 上传图片
            imageUpload : true,
            imageFormats : [ "jpg", "jpeg", "gif", "png", "bmp", "webp" ],
            // 上传图片时指定调用后台的视图函数
            imageUploadURL : "",

        });
    });
</script>
</div>

{% endblock %}

templates/front/front_base.html
<!-- 前台模板页面文件：templates/front/front_base.html  -->

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--  在头文件中接收csrf信息  -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %} {% endblock %}</title>

    <!--  bootstrap支持css，js的样式  -->
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!--  关联front_index.html的css样式  -->
    <link href="{{ url_for('static', filename='front/css/front_index.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='front/css/front_base.css') }}" rel="stylesheet">

    <!--  提示框的静态资源文件  -->
    <link rel="stylesheet" href="{{ url_for('static', filename='common/sweetalert/sweetalert.css') }}">
    <!-- 关联提示框的js样式  -->
    <script src="{{ url_for('static', filename='common/sweetalert/lgalert.js') }}"></script>
    <script src="{{ url_for('static', filename='common/sweetalert/sweetalert.min.js') }}"></script>
    <!-- 导入lgajax.js文件  -->
    <script src="{{ url_for('static', filename='common/lgajax.js') }}"></script>

    <!--  模板继承，补充内容使用  -->
    {% block head %}

    {% endblock %}
</head>
<body>
<!--  bootstrop中复制来的导航条  -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">BBS论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <!--     判断是否登录,没有g对象信息就进行登录           -->
                {% if g.front_user %}
                    <li class="dropdown">
                        <!--   {{ g.front_user.username }}   显示g对象信息 -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ g.front_user.username }}<span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('cms.profile') }}">个人中心</a></li>
                            <li><a href="{{ url_for('cms.index') }}">设置</a></li>
                            <li><a href="{{ url_for('front.index') }}">退出登录</a></li>
                        </ul>
                    </li>
                {% else %}
                    <!--    关联登录注册的url，front.signin是类视图中路由决定     -->
                    <li><a href="{{ url_for('front.signin') }}">登陆</a></li>
                    <li><a href="{{ url_for('front.signup') }}">注册</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--   bootstrop中复制的导航条代码结束 -->

<!-- 模板继承 -->
{% block main_content %}

{% endblock %}
</body>
</html>

templates/front/front_index.html
<!-- 前台首页页面文件：templates/front/front_index.html  -->

{% extends 'front/front_base.html' %}

{% block title %}
首页
{% endblock %}

<!-- 模板继承 -->
{% block main_content %}
<!--   居中样式  -->
<div class="main-container">
    <div class="lg-container">
        <!-- bootstrop中复制来的轮播图  -->
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- 指令 -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- 轮播图 -->
            <div class="carousel-inner" role="listbox">
                <!--    循环apps/front/views.py文件传输的banners数据      -->
                {% for banner in banners %}
                <!--    判断是否第一次循环      -->
                {% if loop.first %}
                <div class="item active">
                    {% else %}
                    <div class="item">
                        {% endif %}
                        <!--    轮播图路径，style="width: 300px;height: 300px"轮播图大小 -->
                        <img src="{{ banner.image_url }}" alt="..." style="width: 300px;height: 300px">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- 轮播图左右切换按钮 -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- bootstrop中复制来的轮播图 代码结束   -->

            <!--   帖子排序方式     -->
            <div class="post-group">
                <ul class="post-group-head">
                    <!--        根据不同种类进行排序,url中传输两个参数st和 board_id           -->
                    {% if current_sort == 1 %}
                        <li class="active"><a href="{{ url_for('front.index', st=1, board_id=current_board) }}">最新</a></li>
                    {% else %}
                        <li class=""><a href="{{ url_for('front.index', st=1, board_id=current_board) }}">最新</a></li>
                    {% endif %}

                    {% if current_sort == 2 %}
                        <li class="active"><a href="{{ url_for('front.index', st=2, board_id=current_board) }}">精华帖子</a></li>
                    {% else %}
                        <li class=""><a href="{{ url_for('front.index', st=2, board_id=current_board) }}">精华帖子</a></li>
                    {% endif %}

                    {% if current_sort == 3 %}
                        <li class="active"><a href="{{ url_for('front.index', st=3, board_id=current_board) }}">阅读最多</a></li>
                    {% else %}
                        <li class=""><a href="{{ url_for('front.index', st=3, board_id=current_board) }}">阅读最多</a></li>
                    {% endif %}

                    {% if current_sort == 4 %}
                        <li class="active"><a href="{{ url_for('front.index', st=4, board_id=current_board) }}">评论最多</a></li>
                    {% else %}
                        <li class=""><a href="{{ url_for('front.index', st=4, board_id=current_board) }}">评论最多</a></li>
                    {% endif %}

                </ul>
                <ul class="post-list-group">
                    <!--         循环帖子信息，首页渲染           -->
                    {% for post in posts %}
                        <li>
                        <div class="author-avatar-group">
                            <img src="#" alt="">
                        </div>
                        <div class="post-info-group">
                            <p class="post-title">
                                <!--  front.post_detail反转需要写的是路由的函数名，post_id=post.id传输帖子id，post_id是名字，post.id是value      -->
                                <a href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>

                            <!--   精华帖判定条件:当前帖子存在highlight这个外联属性     -->
                                {% if post.highlight %}
                                    <span class="label label-danger">精华帖</span>
                                {% endif %}
                            </p>
                            <p class="post-info">
                                <!-- post模型中的author外键调用Front_User中的username信息  -->
                                <span>作者:{{ post.author.username }}</span>
                                <span>发表时间:{{ post.create_time }}</span>
                                <span>评论:{{ comment_count }}</span>
                                <span>阅读:{{ post.read_count }}</span>
                            </p>
                        </div>
                    </li>
                    {% endfor %}

                </ul>
                <div style="text-align:center;">
                <!--       页码分页展示， pagination.links数据由 apps/front/views.py传输过来           -->
                    {{ pagination.links }}
                </div>
            </div>
        </div>

        <!--      帖子标签内容      -->
        <div class="sm-container">
            <div style="padding-bottom:10px;">
                <!--       重定向到/apost/路由，文本编辑界面        -->
                <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>
            </div>
            <div class="list-group">
                <!--      保留st=current_sort用户当前选择的排序方式          -->
                <a href="{{ url_for('front.index', st=current_sort ) }}" class="list-group-item active">所有板块</a>
                <!--     循环显示前台蓝图文件：apps/front/views.py中传输的数据**context           -->
                {% for board in boards %}
                    <!--         注意这里的current_board_id数据类型是int，才能与board.id相比较           -->
                    {% if current_board_id == board.id %}
                        <!--    url_for('front.index', board_id=board.id)每次点击跳转到front_index.html页面，即当前界面，且传输给一个board_id的参数值，由board.id赋值            -->
                        <a href="{{ url_for('front.index', board_id=board.id, st=current_sort ) }}" class="list-group-item active">{{ board.name }}</a>
                    {% else %}
                        <!--  没被选中，即没有被传输相同的board.id，图标样式是class="list-group-item">    -->
                        <a href="{{ url_for('front.index', board_id=board.id, st=current_sort  ) }}" class="list-group-item">{{ board.name }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!--  居中样式  -->
{% endblock %}

templates/front/front_test.html
<!-- 前台测试页面文件：templates/front/front_test.html  -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Referrer跳转测试</title>
</head>
<body>
<!--    关联登录注册的url，front.signin是类视图中路由决定     -->
<a href="{{ url_for('front.signup') }}">Referrer注册跳转测试</a>
<a href="{{ url_for('front.signin') }}">Referrer登录跳转测试</a>

</body>
</html>