apps/cms/forms.py
# -*- encoding: utf-8 -*-
"""
@File    : forms.py
@Time    : 2020/5/11 10:00
@Author  : chen
forms表单信息:apps/cms/forms.py
"""
# forms表单信息
from wtforms import Form, StringField, IntegerField, ValidationError
from wtforms.validators import Email, InputRequired, Length, EqualTo, URL  # EqualTo验证新密码是否相同,URL验证
from utils.redis_captcha import redis_get  # 导入验证码模块


# 创父类form表单，用于输出错误信息
class BaseForm(Form):
    def get_error(self):
        message = self.errors.popitem()[1][0]  # 错误信息的收集，字典类型数据信息提取
        return message


# 登录页面中的Form表单      继承父类form
class LoginForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱"), InputRequired(message="请输入邮箱")])
    password = StringField(validators=[Length(3, 15, message='请输入正确长度的密码')])  # 长度可以先设置短的，方便项目测试
    remember = IntegerField()  # 记住cookie操作  赋值为0或1


# 修改密码页面中的form表单信息    继承父类form
class ResetPwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(3, 15, message="密码长度有误")])
    newpwd = StringField(validators=[Length(3, 15, message="密码长度有误")])
    newpwd2 = StringField(validators=[EqualTo("newpwd", message="两次输入密码不一致")])


# 定义设置邮箱的表单信息，进行提交时候使用
class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确格式的邮箱")])  # 名称email与cms_resetemail.html中的要相同
    captcha = StringField(
        validators=[Length(min=4, max=4, message="请输入正确长度的验证码")])  # 名称captcha与cms_resetemail.html中的要相同
    
    # 验证redis中的字段与数据库中的字段是否相同
    def validate_captcha(self, field):  # 方法命名规则是：validate_字段名()
        # 表单提交上来的验证码
        email = self.email.data
        captcha = self.captcha.data
        
        # 取redis中保存的验证码             第一个redis_captcha是新对象，第二个redis_captcha是redis_captcha.py文件
        redis_captcha = redis_get(email)
        if not redis_captcha or captcha.lower() != redis_captcha.lower():  # 不区分大小写
            raise ValidationError('邮箱验证码错误')


# 定义 添加轮播图 的表单信息
class AddBannerForm(BaseForm):
    # Form表单名称根据static/cms/js/banners.js中的ajax.post发送的data中
    name = StringField(validators=[InputRequired(message="请输入轮播图名称")])
    image_url = StringField(validators=[InputRequired(message="请输入轮播图片链接"), URL(message="图片链接有误")])
    link_url = StringField(validators=[InputRequired(message="请输入轮播图上跳转链接"), URL(message="跳转链接有误")])
    priority = IntegerField(validators=[InputRequired(message="请输入轮播图优先级")])


# 定义 修改轮播图 的表单信息
class UpdateBannerForm(AddBannerForm):        # 继承AddBannerForm,收集表单信息一样，只多出来一个查询字段banner_id
    # 根据banner_id查询 修改 轮播图
    banner_id = IntegerField(validators=[InputRequired(message="轮播图不存在")])
    

# 定义 增加板块管理 的表单信息
class AddBoardsForm(BaseForm):
    # 板块名称
    name = StringField(validators=[InputRequired(message="板块名称不存在")])
    

# 编辑 板块管理名称
class UpdateBoardsForm(AddBoardsForm):
    # 修改编辑板块名称的时候需要使用board_id进行查询，再修改
    board_id = IntegerField(validators=[InputRequired(message="请输入板块ID")])

apps/cms/__init__.py
# -*- encoding: utf-8 -*-
"""
@File    : __init__.py.py
@Time    : 2020/5/11 9:57
@Author  : chen

"""

apps/cms/views.py
# -*- encoding: utf-8 -*-
"""
@File    : views.py
@Time    : 2020/5/11 9:59
@Author  : chen
视图文件:apps/cms/views.py文件
"""
# 蓝图文件：实现模块化应用，应用可以分解成一系列的蓝图   后端的类视图函数写在这个文件
from flask import (
    request, redirect, url_for,                      # 页面跳转redirect   request请求收集
    Blueprint, render_template, views, session,      # 定义类视图，显示模板文件
    jsonify, g                                       # jsonify强制转换成json数据
)
from exts import db, mail                            # 数据库中更新密码、邮箱等使用

from apps.cms.forms import (
    LoginForm, ResetPwdForm,                        # ResetPwdForm修改密码的form信息
    ResetEmailForm,                                 # 导入forms.py文件中的邮箱验证的表单信息类
    AddBannerForm,                                  # 导入 添加轮播图 的表单信息
    UpdateBannerForm,                               # 导入 更新轮播图 的表单信息
    AddBoardsForm,                                  # 导入 增加板块管理 的表单信息
    UpdateBoardsForm,                               # 导入 编辑板块管理 的表单信息
)

from apps.cms.models import (
    CMS_User,                                       # 后台用户模型
    CMSPersmission,                                 # CMSPersmission验证用户不同模块权限
    CMSRole,                                        # 用户角色模型
    BannerModel,                                    # 导入 轮播图模型BannerModel
    BoardModel,                                     # 导入 板块管理模型
    HighlightPostModel,                             # 帖子加精模型
)
# 导入 帖子 模型文件
from apps.front.models import PostModel

from .decorators import permission_required            # 传参装饰器验证用户不同模块权限

# 导入装饰器：判断当前界面是否是登录界面,不是就将url重定向到登录界面,一般不用，使用的主要是钩子函数
from .decorators import login_required

# 导入restful.py中的访问网页状态码的函数          redis_captcha：redis存储、提取、删除验证码功能
from utils import restful, random_captcha, redis_captcha           # 随机生成验证码函数random_captcha()

# 导入flask-mail中的Message
from flask_mail import Message

# 导入clery的异步发送邮件模块
from task import send_mail

cms_bp = Blueprint("cms", __name__, url_prefix='/cms/')     # URL前缀url_prefix

# 钩子函数是在cms_bp创建之后才创建的，顺序在cms_bp创建之后
from .hooks import before_request


@cms_bp.route("/")                                          # 后台界面
# @login_required             # 装饰器判定当前界面是否是登录界面，但是需要每个路由函数都要加该装饰器，比较麻烦，推荐使用钩子函数
def index():
    # return "cms index：后端类视图文件"
    return render_template('cms/cms_index.html')  # 登陆之后进入CMS后台管理界面


# 用户注销登录
@cms_bp.route("/logout/")                              # 需要关联到cms/cms_index.html中的注销属性
def logout():
    # session清除user_id
    del session['user_id']
    # 重定向到登录界面
    return redirect(url_for('cms.login'))             # 重定向(redirec)为把url变为重定向的url


# 定义个人中心的路由
@cms_bp.route("/profile/")
def profile():
    return render_template("cms/cms_profile.html")   # 模板渲染(render_template)则不会改变url，模板渲染是用模板来渲染请求的url


# 定义类视图，显示模板文件   用户登录功能实现
class LoginView(views.MethodView):
    def get(self, message=None):                                         # message=None时候不传输信息到cms_login.html页面
        return render_template("cms/cms_login.html", message=message)    # 针对post方法中同样要返回到cms_login.html页面进行代码简化
    
    # 用户登录操作验证
    def post(self):
        # 收集表单信息
        login_form = LoginForm(request.form)
        if login_form.validate():
            # 数据库验证
            email = login_form.email.data
            password = login_form.password.data
            remember = login_form.remember.data
            
            # 查询数据库中的用户信息
            user = CMS_User.query.filter_by(email=email).first()    # 邮箱唯一，用于查询验证用户
            if user and user.check_password(password):              # 验证用户和密码是否都正确
                session['user_id'] = user.id                        # 查询到用户数据时，保存session的id到浏览器
                # session['user_name'] = user.username                # 将数据库中的user.username保存到session中，在hooks.py中判断
                # session['user_email'] = user.email                  # 将数据库中的email保存到session中,方便html调用信息
                # session['user_join_time'] = user.join_time          # 将数据库中的join_time保存到session中,方便html调用信息
                
                if remember:                                        # 如果用户点击了remember选择，在浏览器中进行数据持久化
                    session.permanent = True                        # 数据持久化，默认31天，需要设置session_key在config.py中
            
                # 登录成功，跳转到后台首页
                return redirect(url_for('cms.index'))               # 在蓝图中必须加cms   跳转到index方法
            else:
                # return "邮箱或密码错误"                              # 登录出错，返回结果
                # return render_template("cms/cms_login.html", message="邮箱或密码错误")  # 登录出错，返回结果渲染到cms_login.html页面
                return self.get(message="邮箱或密码错误")             # 传参到get方法中，多加一个传输错误信息的参数到方法中
        else:
            # print(login_form.errors)                                 # forms.py中的错误信息  字典类型数据
            # print(login_form.errors.popitem())                       # forms.py中的错误信息  元祖类型数据
            # return "表单验证错误"                                     # 错误信息需要渲染到cms_login.html页面
            # return self.get(message=login_form.errors.popitem()[1][0])  # 字典类型数据信息提取
            return self.get(message=login_form.get_error())            # login_form是收集到的表单信息，信息提取放置到forms.py的父类中实现
    
    
# 修改密码的类视图验证
class ResetPwd(views.MethodView):
    def get(self):
        return render_template('cms/cms_resetpwd.html')         # 模板渲染到cms_resetpwd.html
    
    # post提交密码修改
    def post(self):
        # 先审查旧密码是否与数据库中的信息相同
        form = ResetPwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            # 对象
            user = g.cms_user
            # 将用户输入的密码进行加密检测是否与数据库中的相同
            if user.check_password(oldpwd):
                # 更新我的密码  将新密码赋值，此时的新密码已经经过验证二次密码是否一致
                user.password = newpwd         # user.password已经调用了models.py中的 @property装饰器进行密码加密
                # 数据库更新
                db.session.commit()
                # return jsonify({"code": 400, "message": "密码修改成功"})        # 代码改写为下面
                return restful.success("密码修改成功")             # 调用restful.py中定义的访问网页成功的函数
            else:
                # 当前用户输入的旧密码与数据库中的不符
                # return jsonify({"code": 400, "message": "旧密码输入错误"})
                return restful.params_error(message="旧密码输入错误")      # 参数错误
        else:
            # ajax 需要返回一个json类型的数据
            # message = form.errors.popitem()[1][0]                     # 收集错误信息
            # return jsonify({"code": 400, "message": message})         # 将数据转换成json类型
            return restful.params_error(message=form.get_error())       # 参数错误，信息的收集在forms.py的父类函数中实现  form是收集到的信息
        

# 定义修改邮箱的类视图 验证
class ResetEmail(views.MethodView):
    def get(self):
        return render_template("cms/cms_resetemail.html")      # 返回到修改邮箱页面url
    
    def post(self):
        form = ResetEmailForm(request.form)                    # 接收邮箱验证的form表单信息
        if form.validate():                                    # 验证表单信息是否通过
            email = form.email.data                            # 获取form表单中填写的邮箱地址
            
            # 查询数据库
            # CMS_User.query.filter_by(email=email).first()
            # CMS_User.query.filter(CMS_User.email == email).first()
            g.cms_user.email = email                           # 数据库中的查询在apps/cms/hooks.py文件中确定了该用户的数据库信息,用全局对象g.cms_user修改邮箱
            db.session.commit()
            return restful.success()                           # 邮箱修改成功
        else:
            return restful.params_error(form.get_error())      # form是这个类中的所有表单信息
        
        
# 发送测试邮件进行验证
@cms_bp.route("/send_email/")
def send_mail_1():                                                  # 防止与clery中异步发送邮件方法名相同
    message = Message('邮件发送', recipients=['727506892@qq.com'], body='测试邮件发送')   # 主题：邮件发送;收件人：recipients;邮件内容：测试邮件发送
    mail.send(message)                   # 发送邮件
    return "邮件已发送"


# 邮件发送
class EmailCaptcha(views.MethodView):
    def get(self):                                  # 根据resetemail.js中的ajax方法来写函数，不需要post请求
        email = request.args.get('email')           # 查询email参数是否存在
        if not email:
            return restful.params_error('请传递邮箱参数')
        
        # 发送邮件，内容为一个验证码：4、6位数字英文组合
        captcha = random_captcha.get_random_captcha(4)            # 生成4位验证码
        # message = Message('BBS论坛邮箱验证码', recipients=[email], body='您的验证码是：%s' % captcha)
        
        # 异常处理
        try:
            send_mail.delay('BBS论坛邮箱验证码', recipients=[email], body='您的验证码是：%s' % captcha)   # 引用clery异步发送邮件
            # mail.send(message)
        except:
            return restful.server_error(message="服务器错误，邮件验证码未发送！")   # 发送异常，服务器错误
        
        # 验证码保存，一般有时效性，且频繁请求变化，所以保存在Redis中
        redis_captcha.redis_set(key=email, value=captcha)        # redis中都是键值对类型，存储验证码
        return restful.success("邮件验证码发送成功！")
    

# 轮播图管理路由
@cms_bp.route("/banners/")
def banners():
    # 通过模型中定义的权重priority的倒叙来排序
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template("cms/cms_banners.html", banners=banners)           # 传输banners数据到cms_banners.html界面渲染


# 添加轮播图功能路由，且方法需要与static/cms/js/banners.js中绑定的方法POST相同
@cms_bp.route("/abanner/", methods=['POST'])
def abanner():
    form = AddBannerForm(request.form)                  # 接收添加轮播图的form表单信息
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)     # 轮播图模型
        db.session.add(banner)                                                                         # 提交数据库
        db.session.commit()
        return restful.success()                                                                       # 轮播图信息提交成功
    else:
        return restful.params_error(message=form.get_error())                                          # 表单信息错误


# 修改 轮播图 路由，方法与static/cms/js/banners.js中绑定的方法POST相同
@cms_bp.route("/ubanner/", methods=['POST'])
def ubanner():
    # 修改根据banner_id查询再修改

templates/cms/cms_banners.html
<!--  后端 -->
{% extends 'cms/cms_base.html' %}

{% block title %}
    轮播图管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block head %}
    <!--  七牛云初始化文件,七牛云为javascript提供了一个专门用来传文件的接口  -->
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ url_for('static', filename='common/lgqiniu.js') }}"></script>
    <script src="{{ url_for('static',filename='cms/js/banners.js') }}"></script>
    <style>
        .top-box button{
            float: right;
        }
    </style>
{% endblock %}

{% block content %}


<div class="top-box">
    <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>名称</th>
        <th>图片链接</th>
        <th>跳转链接</th>
        <th>优先级</th>
        <th>创建时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <!--   循环数据库中banners信息,数据从视图文件:apps/cms/views.py中传输渲染过来 -->
    {% for banner in banners %}
        <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}"
            data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
            <td>{{ banner.name }}</td>

            <!--     truncate(length=20)将链接的显示长度控制在20字符       -->
            <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url|truncate(length=20) }}</a></td>
            <!--     轮播图跳转链接显示  权重、创建时间     -->
            <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
            <td>{{ banner.priority }}</td>
            <td>{{ banner.create_time }}</td>

            <td>
                <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">轮播图</h4>
            </div>
            <div class="modal-body">
                <form action="" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">名称：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">图片：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                        </div>
                        <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">跳转：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">权重：</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" name="priority" placeholder="优先级">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/cms/cms_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--  在头文件中接收csrf信息  -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}

    {% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--  关联本地的cms_base.css样式 后台管理界面CMS的样式 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='cms/css/cms_base.css') }}">
<!--  关联本地的cms_base.js样式 后台管理界面CMS的样式 -->
    <script src="{{ url_for('static', filename='cms/js/cms_base.js') }}"></script>

<!--  提示框的静态资源文件  -->
    <link rel="stylesheet" href="{{ url_for('static', filename='common/sweetalert/sweetalert.css') }}">
<!-- 关联提示框的js样式  -->
    <script src="{{ url_for('static', filename='common/sweetalert/lgalert.js') }}"></script>
    <script src="{{ url_for('static', filename='common/sweetalert/sweetalert.min.js') }}"></script>
<!-- 导入lgajax.js文件  -->
    <script src="{{ url_for('static', filename='common/lgajax.js') }}"></script>

<!--  预留空间，给之后的html文件进行修改调整  -->
    {% block head %}

    {% endblock %}

</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
        <!--       从数据库中调用用户名，g对象全局调用g.cms_user对象  .username是该对象的一个字段属性      -->
            <li><a href="#">{{ g.cms_user.username }}</a></li>

        <!--  用户注销，关联到views.py中的@cms_bp.route("/logout/")路由,重定向到该路由      -->
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="#">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">

                        <!--          url重定向到/cms/profile/下   路由在views.py中定义了       -->
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <!--         密码修改的url_for 重定向到/cms/resetpwd/  路由在views.py中定义了           -->
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <!--         重定向到修改邮箱的url_for=/cms/resetemail/        -->
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                  <!--  将全局变量的对象命名为user  -->
                  {% set user = g.cms_user %}
                    <!--        {{ url_for('cms.banners') }}绑定路由          -->
                  <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>

                  <!--    判断是否有权限进行管理后台，CMSPersmission.ALL_PERMISSION并没有传输过来，无法识别，需要用到钩子函数中的上下文管理器，在hooks.py中编写 -->
                  {% if  user.has_permissions(CMSPersmission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                  {% endif %}

                  {% if  user.has_permissions(CMSPersmission.COMMENTER) %}
                    <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                  {% endif %}

                  {% if  user.has_permissions(CMSPersmission.BOARDER) %}
                    <!--        {{ url_for('cms.boards') }}关联路由          -->
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                  {% endif %}

                  {% if  user.has_permissions(CMSPersmission.FRONTUSER) %}
                    <li class="nav-group user-manage"><a href="{{ url_for('cms.fuser') }}">前台用户管理</a></li>
                  {% endif %}

                  {% if  user.has_permissions(CMSPersmission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cuser') }}">CMS用户管理</a></li>
                  {% endif %}

                  {% if  user.is_developer %}
                    <li class="cmsrole-manage"><a href="{{ url_for('cms.profile') }}">CMS组管理</a></li>
                  {% endif %}

            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}

            {% endblock %}</h1>
            <div class="main_content">
                {% block content %}

                {% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_boards.html
<!--  继承模板文件cms/cms_base.html  简化代码 -->
{% extends 'cms/cms_base.html' %}

<!-- 页面标题 -->
{% block title %}
    板块管理
{% endblock %}

<!--  标题  -->
{% block page_title %}
    {{self.title()}}
{% endblock %}


{% block head %}
<script src="{{ url_for('static', filename='cms/js/boards.js') }}"></script>
{% endblock %}

{% block content %}
<div class="top-box">
    <button class="btn btn-warning" style="float:right;" id="add-board-btn">添加新板块</button>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>板块名称</th>
        <th>帖子数量</th>
        <th>创建时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <!--  循环board信息，boards数据由视图文件:apps/cms/views.py文件传输而来 -->
    {% for board in boards %}
        <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
            <td>{{ board.name }}</td>
            <td>0</td>
            <td>{{ board.create_time }}</td>
            <td>
                <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/cms/cms_comments.html
<!--  继承模板文件cms/cms_base.html  简化代码 -->
{% extends 'cms/cms_base.html' %}

<!-- 页面标题 -->
{% block title %}
    评论管理
{% endblock %}

<!--  标题  -->
{% block page_title %}
    {{self.title()}}
{% endblock %}


{% block content %}

{% endblock %}

templates/cms/cms_cuser.html
<!--  继承模板文件cms/cms_base.html  简化代码 -->
{% extends 'cms/cms_base.html' %}

<!-- 页面标题 -->
{% block title %}
    后台用户管理
{% endblock %}

<!--  标题  -->
{% block page_title %}
    {{self.title()}}
{% endblock %}


{% block content %}

{% endblock %}

templates/cms/cms_fuser.html
<!--  继承模板文件cms/cms_base.html  简化代码 -->
{% extends 'cms/cms_base.html' %}

<!-- 页面标题 -->
{% block title %}
    前台用户管理
{% endblock %}

<!--  标题  -->
{% block page_title %}
    {{self.title()}}
{% endblock %}


{% block content %}

{% endblock %}

templates/cms/cms_index.html
<!--  继承模板文件cms/cms_base.html  简化代码 -->
{% extends 'cms/cms_base.html' %}

<!-- 页面标题 -->
{% block title %}
    CMS管理系统
{% endblock %}

<!--  标题  -->
{% block page_title %}
    欢迎来到CMS管理系统
{% endblock %}

<!-- 内容 -->
{% block content %}
    <!-- 引用相同的内容  -->
    {{ self.page_title() }}
{% endblock %}

templates/cms/cms_permissions.html
<!--  继承模板文件cms/cms_base.html  简化代码 -->
{% extends 'cms/cms_base.html' %}

<!-- 页面标题 -->
{% block title %}
    权限管理
{% endblock %}

<!--  标题  -->
{% block page_title %}
    {{self.title()}}
{% endblock %}


{% block content %}

{% endblock %}